language: python
python: 3.5.2
sudo: false
env:
- LOCAL_SETTINGS=settings_local_travis
install:
- pip install -r requirements.txt
script:
- nosetests
notifications:
  slack:
    secure: a0yHUEYqrxx2IX1mvH54jEjDDKm/d/zlGa/7Zp7fXUdboqCf2gHgk/NV8mBPJHEPhhANKO80i39Vk5A9M+hd16w47gax+LsaLKK0W4g6/dKg6VcioVIChF9a6t4czhK8l2FJuh5AGwoYKhuBynb89ucap1biWlGIY+1eFCNDZ8BpUjJZVveENMhKqjoiabilDXznqJlJp7Q/PbjUWUJasGRNeY+/R+FT6pqplA0wYoeHeER793vDcVgr4Luek30IqexUjWEGjYFlJ8Y9cgsSDojiqVHA21n7AwCYCQ8RGFCTlhHYrF5eu6820jEB42gZr6D9JC2erOiSnF78nwz7Pbq1dwpxr73gCI/qtOWlVAHxAQvoph3dIRPzoVuLhi58mz4Kx334gOQAMsN33VGvHUIEL29WslyH+mZKkr+HoNGQhdFr/uO7PG9OEJXOqtty0lq4m9t2xe/nt4HovHiXanB8hjdiHOLnkuQ4bjwMmed0WjO+FN5Kkki4Y40KJCr0E8ZusTUrZp9yqZQ430W9iSBFIV8PpBF1zMhYDTAR7lUWS9zwXjK8bB99UnAmTtiiWGoxwVxydqAtOASmyl8YLMVwHs+57EkTzjFR7/W3pntsqeTO8AClxBAaSTDmiG+r6RQaAaugFDs82rQIIATd2BywjW4TJpGA2TOxKW+f6H4=
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch:
    - master
cache:
  directories:
  - "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages"
